-- AlterTable
ALTER TABLE "comment" ADD COLUMN     "commentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "post" ADD COLUMN     "postDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
